### ISSUE TITLE
Rainbow Facets

### ISSUE THREAD

**Issue by narfbg** [Nasicus/d2-holy-grail#22]
The app has listed 4 Rainbow Facets, one for each type of elemental damage. While this would make sense if the CtC on death/level-up was a random affix on them, that's not really the case and the actual count of unique jewels (i.e. facets) is 8, the only random affixes being the percentage ranges for damage/negative resists.

This is easily verifiable by looking at the game files ([convenient link](https://github.com/fabd/diablo2/blob/e67aa992be5db412bd0437bb8afb95eedee0c9bc/code/d2_113_data/UniqueItems.txt#L394)). Drop calculators such as http://dropcalc.silospen.com/item.php, http://mfb.bplaced.net/dropcalc/dropcalc.php?lang=en and the one in ATMA also make this distinction.

This creates 2 problems:

1. The actual number of grail items should be 506, not the current 502.
2. Fixing it isn't as easy as simply adding the 4 new types, because people have already marked 4 types of facets as found, without the necessary CtC on death/level-up distinction. This is also why I'm not just submitting a PR.

The optimal solution would be to replace the current 4 with a new array of 8 facets, making sure there's no way for someone who's already ticked them to match the old ones, and then emailing users about the change, but IIRC that's not possible as the app doesn't collect emails on registration.
On that note, kudos for completely detaching yourself from privacy issues, though it does also mean if I ever forget my password I'm kinda screwed. :D If you decide to change that, I'd be happy to help you with the security-related issues that come with it as I do have expertise in the area.

So, I suppose the doable solution is to put up a notice on the site instead of emailing, maybe using a cookie to determine who has seen it and who hasn't?

**Comment by Nasicus** [comment]
Actually the fix would be as easy as simply adding the 4 news items / changing the existing ones.
Because displaying the grail (as far as I remember :P) is not based on the actual definition of the files, but on the "instance" of your grail config which is returned from the server / you ahve in the cache.
So I think existing users would not be affected at all. (Which is both good and bad...well in this case good).

I'm just not sure if we should really do that. I had discussions in discord about this already. I personally don't have a strong opinion. But if we do it I just want to be really sure that 8 is correct.... based on your links it is... so maybe you're right. => so imho it can be done.

Concerning the password things:
Yes it's a cheap solution.... I actually never thought people would really use this site at all -  but just in case I added the not already in the very beginning ;)

It's also not like I don't know how to secure the app, I just didn't find it necessary until now - and I still don't.
One user actually forgot his PW once and wrote to me in discord... I then reset it ;)
But if you feel strong about this and want to do it... feel free to start working on it / we can also discuss it further :)

**Comment by narfbg** [comment]
There's no way for current users to be unaffected ... I assume you mean the site won't break for them, in which case - yes, even if there was an implementation detail that would cause a breakage, that would be easily correctable with a small script to update current data.
However, a person who has marked e.g. a "Cold" faced as owned will now no longer have it marked in their gail list - that's a BC break, hence my suggestion for some kind of a notification.

As for the password-related stuff ... I've never met a developer who doesn't think they can "secure" an app, while in reality most implementations are not up to respectable standards. :) Either way, I guess it's fine as it is now; that was really just an on the side remark as I was thinking of email notifications.

**Comment by Nasicus** [comment]
No it doesn't have an impact actually :)

I tested it locally.

So that's an old grail locally:
![image](https://user-images.githubusercontent.com/1086065/59962241-f8d8fa80-94e2-11e9-9f61-215276520cde.png)
![image](https://user-images.githubusercontent.com/1086065/59962252-1c9c4080-94e3-11e9-864b-ee5a74ff37ed.png)

Then I updated the code and created a new grail locally:
![image](https://user-images.githubusercontent.com/1086065/59962258-32aa0100-94e3-11e9-866e-c1eee64c617b.png)
![image](https://user-images.githubusercontent.com/1086065/59962268-3f2e5980-94e3-11e9-8fea-2bc9ea3556e7.png)

The only thing left to do, would actually be to make the "API" work with the new / old versions.

**Comment by narfbg** [comment]
What? One has to create an entirely new grail to track? That's the least convenient solution for users.

**Comment by Nasicus** [comment]
Well no. 
It's still possible to migrate their holidaygrail (automatically) to the new grail version.
For example we could also define, that if you have checked the jewels on the old version, that on the new version we will just check both level up and die or something like this.

**Comment by narfbg** [comment]
And that's where the BC break I was talking about comes into play. :)

Just in the interest of someone not mistakingly having their grail marked as complete by accident, I would suggest to have neither marked and simply display a notification about the change, so users can mark the correct items accordingly.

**Comment by Nasicus** [comment]
I will think about it.

Maybe I will have a sudden burst of motivation to implement it ;)

**Comment by Nasicus** [comment]
Done & released

**Comment by narfbg** [comment]
Awesome, thanks!
