### ISSUE TITLE
assassin is spelled incorrectly assasin under $.grail.uniques.other.classes

### ISSUE THREAD

**Issue by RecycleFix** [Nasicus/d2-holy-grail#97]
assassin is spelled with 3*s instead of 4.

**Comment by Nasicus** [comment]
This has already been fixed in the code, however the thing is that all existing grails (as soon you you create one) copies the "current state" of these into the json, therefore it's not fixd in there.

If it's important to  yourself you could fix the json and the manually make an api call to fix it for your own grail

**Comment by RecycleFix** [comment]
Thanks for the feedback.
Glad you already fixed it - I'll submit my json with it spelled correctly.
